name: video-outreach-gen
description: Serverless project for cold outreach video generator
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
